// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"time"
)

type Campaign struct {
	ID            int64     `json:"id"`
	OwnerID       int64     `json:"ownerId"`
	Name          string    `json:"name"`
	Description   *string   `json:"description"`
	Visibility    string    `json:"visibility"`
	Status        string    `json:"status"`
	ActiveSceneID *int64    `json:"activeSceneId"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type CampaignCharacter struct {
	ID          int64     `json:"id"`
	CampaignID  int64     `json:"campaignId"`
	CharacterID int64     `json:"characterId"`
	CreatedAt   time.Time `json:"createdAt"`
}

type CampaignHandout struct {
	ID          int64     `json:"id"`
	CampaignID  int64     `json:"campaignId"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	FilePath    *string   `json:"filePath"`
	CreatedBy   int64     `json:"createdBy"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type CampaignInvite struct {
	ID          int64      `json:"id"`
	CampaignID  int64      `json:"campaignId"`
	Code        string     `json:"code"`
	InvitedBy   int64      `json:"invitedBy"`
	RoleDefault string     `json:"roleDefault"`
	Status      string     `json:"status"`
	ExpiresAt   time.Time  `json:"expiresAt"`
	RedeemedBy  *int64     `json:"redeemedBy"`
	RedeemedAt  *time.Time `json:"redeemedAt"`
	CreatedAt   time.Time  `json:"createdAt"`
}

type CampaignMember struct {
	ID         int64     `json:"id"`
	CampaignID int64     `json:"campaignId"`
	UserID     int64     `json:"userId"`
	Role       string    `json:"role"`
	Status     string    `json:"status"`
	InvitedBy  *int64    `json:"invitedBy"`
	CreatedAt  time.Time `json:"createdAt"`
}

type Character struct {
	ID                       int64     `json:"id"`
	UserID                   int64     `json:"userId"`
	Name                     string    `json:"name"`
	Race                     string    `json:"race"`
	Class                    string    `json:"class"`
	Level                    int64     `json:"level"`
	Background               *string   `json:"background"`
	Alignment                *string   `json:"alignment"`
	ExperiencePoints         *int64    `json:"experiencePoints"`
	Strength                 int64     `json:"strength"`
	Dexterity                int64     `json:"dexterity"`
	Constitution             int64     `json:"constitution"`
	Intelligence             int64     `json:"intelligence"`
	Wisdom                   int64     `json:"wisdom"`
	Charisma                 int64     `json:"charisma"`
	MaxHp                    int64     `json:"maxHp"`
	CurrentHp                int64     `json:"currentHp"`
	TempHp                   *int64    `json:"tempHp"`
	ArmorClass               int64     `json:"armorClass"`
	Speed                    *int64    `json:"speed"`
	HitDice                  *string   `json:"hitDice"`
	SkillProficiencies       *string   `json:"skillProficiencies"`
	SavingThrowProficiencies *string   `json:"savingThrowProficiencies"`
	Features                 *string   `json:"features"`
	Equipment                *string   `json:"equipment"`
	AvatarUrl                *string   `json:"avatarUrl"`
	CreatedAt                time.Time `json:"createdAt"`
	UpdatedAt                time.Time `json:"updatedAt"`
}

type Layer struct {
	ID     int64  `json:"id"`
	MapID  int64  `json:"mapId"`
	Type   string `json:"type"`
	ZIndex int64  `json:"zIndex"`
	Data   string `json:"data"`
}

type Map struct {
	ID           int64     `json:"id"`
	SceneID      int64     `json:"sceneId"`
	Name         string    `json:"name"`
	BaseImageUrl *string   `json:"baseImageUrl"`
	GridSizeFt   int64     `json:"gridSizeFt"`
	WidthPx      *int64    `json:"widthPx"`
	HeightPx     *int64    `json:"heightPx"`
	LightingMode string    `json:"lightingMode"`
	FogState     string    `json:"fogState"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Note struct {
	ID         int64     `json:"id"`
	UserID     int64     `json:"userId"`
	EntityType string    `json:"entityType"`
	EntityID   *int64    `json:"entityId"`
	Title      string    `json:"title"`
	Body       string    `json:"body"`
	CreatedAt  time.Time `json:"createdAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type NoteFt struct {
	Title      string `json:"title"`
	Body       string `json:"body"`
	EntityType string `json:"entityType"`
}

type Scene struct {
	ID          int64     `json:"id"`
	CampaignID  int64     `json:"campaignId"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Ordering    int64     `json:"ordering"`
	IsActive    bool      `json:"isActive"`
	CreatedBy   *int64    `json:"createdBy"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Token struct {
	ID          int64     `json:"id"`
	MapID       int64     `json:"mapId"`
	CharacterID *int64    `json:"characterId"`
	Label       string    `json:"label"`
	ImageUrl    *string   `json:"imageUrl"`
	SizeSquares int64     `json:"sizeSquares"`
	PositionX   int64     `json:"positionX"`
	PositionY   int64     `json:"positionY"`
	FacingDeg   int64     `json:"facingDeg"`
	Audience    string    `json:"audience"`
	Tags        string    `json:"tags"`
	Notes       *string   `json:"notes"`
	Layer       string    `json:"layer"`
	CreatedBy   *int64    `json:"createdBy"`
	CreatedAt   time.Time `json:"createdAt"`
}

type User struct {
	ID           int64     `json:"id"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"passwordHash"`
	CreatedAt    time.Time `json:"createdAt"`
}
